// Generated by CoffeeScript 1.4.0
/*
Copyright (c) 2012 [DeftJS Framework Contributors](http://deftjs.org)
Open source under the [MIT License](http://en.wikipedia.org/wiki/MIT_License).
*/

/**
* A lightweight Application template class.
*/

Ext.define('Deft.mvc.Application', {
  alternateClassName: ['Deft.Application'],
  /**
  	* Indicates whether this Application instance has been initialized.
  */

  initialized: false,
  /**
  	* @param {Object} [config] Configuration object.
  */

  constructor: function(config) {
    if (config == null) {
      config = {};
    }
    this.initConfig(config);
    Ext.onReady(function() {
      this.init();
      this.initialized = true;
    }, this);
    return this;
  },
  /**
  	* Initialize the Application
  */

  init: function() {
    var injectorConfig;
    this.beforeInit();
    injectorConfig = this.buildInjectorConfig();
    if (injectorConfig != null) {
      Deft.Injector.configure(injectorConfig);
    }
    return this.afterInit();
  },
  /**
  * @protected
  * Returns the configuration object to pass to Deft.Injector.configure(). Override in subclasses to alter the Injector configuration before returning the config object.
  * @param {Object} injectorConfig
  * @return {Object} The Injector configuration object.
  */

  buildInjectorConfig: function(injectorConfig) {
    return injectorConfig;
  },
  /**
  * @protected
  * Runs at the start of the init() method. Override in subclasses if needed.
  */

  beforeInit: function() {},
  /**
  * @protected
  * Runs at the end of the init() method. Override in subclasses. Useful to create initial Viewport, start Jasmine tests, etc.
  */

  afterInit: function() {}
});
