// Generated by CoffeeScript 1.4.0
/*
Copyright (c) 2012 [DeftJS Framework Contributors](http://deftjs.org)
Open source under the [MIT License](http://en.wikipedia.org/wiki/MIT_License).
*/

/**
* A Deferred manages the state of an asynchronous process that will eventually be exposed to external code via a Deft.promise.Promise.
*/

Ext.define('Deft.promise.Deferred', {
  alternateClassName: ['Deft.Deferred'],
  requires: ['Deft.log.Logger', 'Deft.promise.Promise'],
  id: null,
  constructor: function(config) {
    if (config == null) {
      config = {};
    }
    this.id = config.id;
    this.state = 'pending';
    this.progress = void 0;
    this.value = void 0;
    this.progressCallbacks = [];
    this.successCallbacks = [];
    this.failureCallbacks = [];
    this.cancelCallbacks = [];
    this.promise = Ext.create('Deft.Promise', {
      id: this.id ? "of " + this.id : null,
      deferred: this
    });
    return this;
  },
  /**
  	* Returns a new {@link Deft.promise.Promise} with the specified callbacks registered to be called when this {@link Deft.promise.Deferred} is resolved, rejected, updated or cancelled.
  */

  then: function(callbacks) {
    var callback, cancelCallback, deferred, failureCallback, progressCallback, scope, successCallback, _i, _len, _ref;
    if (Ext.isObject(callbacks)) {
      successCallback = callbacks.success, failureCallback = callbacks.failure, progressCallback = callbacks.progress, cancelCallback = callbacks.cancel, scope = callbacks.scope;
    } else {
      successCallback = arguments[0], failureCallback = arguments[1], progressCallback = arguments[2], cancelCallback = arguments[3], scope = arguments[4];
    }
    _ref = [successCallback, failureCallback, progressCallback, cancelCallback];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      callback = _ref[_i];
      if (!(Ext.isFunction(callback) || callback === null || callback === void 0)) {
        Ext.Error.raise({
          msg: "Error while registering callback with " + this + ": a non-function specified."
        });
      }
    }
    deferred = Ext.create('Deft.promise.Deferred', {
      id: "transformed result of " + this
    });
    this.register(this.wrapCallback(deferred, successCallback, scope, 'success', 'resolve'), this.successCallbacks, 'resolved', this.value);
    this.register(this.wrapCallback(deferred, failureCallback, scope, 'failure', 'reject'), this.failureCallbacks, 'rejected', this.value);
    this.register(this.wrapCallback(deferred, cancelCallback, scope, 'cancel', 'cancel'), this.cancelCallbacks, 'cancelled', this.value);
    this.register(this.wrapProgressCallback(deferred, progressCallback, scope), this.progressCallbacks, 'pending', this.progress);
    Deft.Logger.log("Returning " + (deferred.getPromise()) + ".");
    return deferred.getPromise();
  },
  /**
  	* Returns a new {@link Deft.promise.Promise} with the specified callback registered to be called when this {@link Deft.promise.Deferred} is rejected.
  */

  otherwise: function(callback, scope) {
    var _ref;
    if (Ext.isObject(callback)) {
      _ref = callback, callback = _ref.fn, scope = _ref.scope;
    }
    return this.then({
      failure: callback,
      scope: scope
    });
  },
  /**
  	* Returns a new {@link Deft.promise.Promise} with the specified callback registered to be called when this {@link Deft.promise.Deferred} is either resolved, rejected, or cancelled.
  */

  always: function(callback, scope) {
    var _ref;
    if (Ext.isObject(callback)) {
      _ref = callback, callback = _ref.fn, scope = _ref.scope;
    }
    return this.then({
      success: callback,
      failure: callback,
      cancel: callback,
      scope: scope
    });
  },
  /**
  	* Update progress for this {@link Deft.promise.Deferred} and notify relevant callbacks.
  */

  update: function(progress) {
    Deft.Logger.log("" + this + " updated with progress: " + progress);
    if (this.state === 'pending') {
      this.progress = progress;
      this.notify(this.progressCallbacks, progress);
    } else {
      if (this.state !== 'cancelled') {
        Ext.Error.raise({
          msg: "Error: this " + this + " has already been completed and cannot be modified."
        });
      }
    }
  },
  /**
  	* Resolve this {@link Deft.promise.Deferred} and notify relevant callbacks.
  */

  resolve: function(value) {
    Deft.Logger.log("" + this + " resolved with value: " + value);
    this.complete('resolved', value, this.successCallbacks);
  },
  /**
  	* Reject this {@link Deft.promise.Deferred} and notify relevant callbacks.
  */

  reject: function(error) {
    Deft.Logger.log("" + this + " rejected with error: " + error);
    this.complete('rejected', error, this.failureCallbacks);
  },
  /**
  	* Cancel this {@link Deft.promise.Deferred} and notify relevant callbacks.
  */

  cancel: function(reason) {
    Deft.Logger.log("" + this + " cancelled with reason: " + reason);
    this.complete('cancelled', reason, this.cancelCallbacks);
  },
  /**
  	* Get this {@link Deft.promise.Deferred}'s associated {@link Deft.promise.Promise}.
  */

  getPromise: function() {
    return this.promise;
  },
  /**
  	* Get this {@link Deft.promise.Deferred}'s current state.
  */

  getState: function() {
    return this.state;
  },
  /**
  	* Returns a text representation of this {@link Deft.promise.Deferred}, including its optional id.
  */

  toString: function() {
    if (this.id != null) {
      return "Deferred " + this.id;
    }
    return "Deferred";
  },
  /**
  	* Wraps a success, failure or cancel callback.
  	* @private
  */

  wrapCallback: function(deferred, callback, scope, callbackType, action) {
    var self;
    self = this;
    if (callback != null) {
      Deft.Logger.log("Registering " + callbackType + " callback for " + self + ".");
    }
    return function(value) {
      var result;
      if (Ext.isFunction(callback)) {
        try {
          Deft.Logger.log("Calling " + callbackType + " callback registered for " + self + ".");
          result = callback.call(scope, value);
          if (result instanceof Ext.ClassManager.get('Deft.promise.Promise') || result instanceof Ext.ClassManager.get('Deft.promise.Deferred')) {
            Deft.Logger.log("" + (deferred.getPromise()) + " will be completed based on the " + result + " returned by the " + callbackType + " callback.");
            result.then(Ext.bind(deferred.resolve, deferred), Ext.bind(deferred.reject, deferred), Ext.bind(deferred.update, deferred), Ext.bind(deferred.cancel, deferred));
          } else {
            Deft.Logger.log("" + (deferred.getPromise()) + " resolved with the value returned by the " + callbackType + " callback: " + result + ".");
            deferred.resolve(result);
          }
        } catch (error) {
          if (Ext.Array.contains(['RangeError', 'ReferenceError', 'SyntaxError', 'TypeError'], error.name)) {
            Deft.Logger.error("Error: " + callbackType + " callback for " + self + " threw: " + (error.stack != null ? error.stack : error));
          } else {
            Deft.Logger.log("" + (deferred.getPromise()) + " rejected with the Error returned by the " + callbackType + " callback: " + error);
          }
          deferred.reject(error);
        }
      } else {
        Deft.Logger.log("" + (deferred.getPromise()) + " resolved with the value: " + value + ".");
        deferred[action](value);
      }
    };
  },
  /**
  	* Wraps a success, failure or cancel callback.
  	* @private
  */

  wrapProgressCallback: function(deferred, callback, scope) {
    var self;
    self = this;
    if (callback != null) {
      Deft.Logger.log("Registering progress callback for " + self + ".");
    }
    return function(value) {
      var result;
      if (Ext.isFunction(callback)) {
        try {
          Deft.Logger.log("Calling progress callback registered for " + self + ".");
          result = callback.call(scope, value);
          Deft.Logger.log("" + (deferred.getPromise()) + " updated with progress returned by the progress callback: " + result + ".");
          deferred.update(result);
        } catch (error) {
          Deft.Logger.error("Error: progress callback registered for " + self + " threw: " + (error.stack != null ? error.stack : error));
        }
      } else {
        Deft.Logger.log("" + (deferred.getPromise()) + " updated with progress: " + value);
        deferred.update(value);
      }
    };
  },
  /**
  	* Register a callback for this {@link Deft.promise.Deferred} for the specified callbacks and state, immediately notifying with the specified value (if applicable).
  	* @private
  */

  register: function(callback, callbacks, state, value) {
    if (Ext.isFunction(callback)) {
      if (this.state === 'pending') {
        callbacks.push(callback);
        if (this.state === state && value !== void 0) {
          this.notify([callback], value);
        }
      } else {
        if (this.state === state) {
          this.notify([callback], value);
        }
      }
    }
  },
  /**
  	* Complete this {@link Deft.promise.Deferred} with the specified state and value.
  	* @private
  */

  complete: function(state, value, callbacks) {
    if (this.state === 'pending') {
      this.state = state;
      this.value = value;
      this.notify(callbacks, value);
      this.releaseCallbacks();
    } else {
      if (this.state !== 'cancelled') {
        Ext.Error.raise({
          msg: "Error: this " + this + " has already been completed and cannot be modified."
        });
      }
    }
  },
  /**
  	* Notify the specified callbacks with the specified value.
  	* @private
  */

  notify: function(callbacks, value) {
    var callback, _i, _len;
    for (_i = 0, _len = callbacks.length; _i < _len; _i++) {
      callback = callbacks[_i];
      callback(value);
    }
  },
  /**
  	* Release references to all callbacks registered with this {@link Deft.promise.Deferred}.
  	* @private
  */

  releaseCallbacks: function() {
    this.progressCallbacks = null;
    this.successCallbacks = null;
    this.failureCallbacks = null;
    this.cancelCallbacks = null;
  }
});
